### ISSUE TITLE
Nav

### ISSUE THREAD

**Issue by CharityBunyon** [nss-evening-cohort-10/nutshell-nautilus-explorer#11]
User Story
As a user, I would like to be able to see the brand on the navBar of the Dashboard, I would also like the logout and login button on the navBar.

AC
WHEN I navigate to the navbar I should see a Nautilus logo/brand on the left.
THEN I should also be able to click on the login button.
AND when I am logged in the button label should change to logout.
AND I should be able to click the logout button on the right and the button change to login (functionality for that is listed in #28)

Dev Notes

added navbar from bootstrap to the index.html file
add <button class="nav-link btn btn-danger hide" id="navbar-button-logout">Log Out</button>
add styling to the navbar in scss file
add Nautilus to right with margins appx~ 1em
navbar - orange background, white font
button - white background and red font

**Comment by aleshakay** [comment]
User Story
As a user, I would like to be able to see the brand on the navBar of the Dashboard, I would also like the logout and login button on the navBar.

AC
WHEN I navigate to the navbar I should see a Nautilus logo/brand on the left.
THEN I should also be able to click on the login and logout button on the right.

Dev Notes
* added navbar from bootstrap to the index.html file 
* add ```<button class="nav-link btn btn-danger hide" id="navbar-button-logout">Log Out</button>```
* add styling to the navbar in scss file
* add Nautilus to right with margins  appx~ 1em
* navbar - orange background, white font
* button - white background and red font

**Comment by aleshakay** [comment]
![image](https://user-images.githubusercontent.com/39807157/68817596-cbcee500-0647-11ea-9d76-3f6ab88ba69b.png)
