### ISSUE TITLE
READ - excursions

### ISSUE THREAD

**Issue by denzelb5** [nss-evening-cohort-10/nutshell-nautilus-explorer#77]
# User Story:
As a user, if I am not logged in, when I open the excursions page I should see cards of all the recent excursions the nautilus has been on. 

# AC:
**WHEN** the page loads,
**AND** I am logged out,
**THEN**  excursions will appear in card format. I should be able to click on an excursion and read about it.  

# Dev Notes:
* Use bootstrap cards for excursions.  The name, image, brief synopsis and destination of the excursion should appear on the card when the user is logged out.  Info should be pulled from firebase to fill the card.
* create an excursionsData file with a getExcursionsData() function to convert firebase objects. Export getExcursionsData().
* create an excursionCards.js module with an excursionCards() 
function.  This function should contain an if/else statement checking if the user is logged in. The if statement checks if the user is logged in. If so, the domstring should include an edit button (yellow) and a delete button (red).  In the else statement the buttons are left out.  
*****

const userSignedIn = firebase.auth().currentUser;
  if (userSignedIn) {
     *bootstrap card elements with edit and delete buttons included here*
} else {
   *no edit and delete buttons included*
}
*****

* create a printExcursionCards() function in the excursions.js module that calls  excursionCards(), getExcursionsData() and prints them to the DOM.  Export printExcursionCards() and call printExcursionCards() in the authData.js file.
*****
const printExcursionCards = () => {
excursionsData.getExcursionsData()
    .then((excursions) => {
      let domString = ' ';
      domString = '<h1 class="text-center" id="excursions-     header">Excursions</h1>';
        domString += ' <div class="cardZone d-flex flex-wrap justify-content-center" id="excursionsCards">';
      }
      excursions.forEach((excursion) => {
        domString += excursionsCard.excursionsCard(excursion);
      });
      domString += '</div>';
utilities.printToDom('excursions', domString);
})
.catch((error) => console.error(error));
};

**Comment by ivannio** [comment]
support tickets: #80 #82 #87

**Comment by gregkorte** [comment]
In dev notes:
Bullet 1: Data should be pulled from firebase?

**Comment by phillipsja97** [comment]
updated the devNote to notate that the info will be pulled from firebase, not the .json file.
