### ISSUE TITLE
Species/Environment - Join Table Data

### ISSUE THREAD

**Issue by denzelb5** [nss-evening-cohort-10/nutshell-nautilus-explorer#80]
# User Story:
N/A

# AC:
Combine species and environment into one table.

# Dev Notes:
* Create a file that lives in the base.json called speciesEnvironment.json.
* Seed that data to firebase.
* Create a file that lives in helpers/data/speciesEnvironmentData.json.
* Inside of that file we will:
    1) Create a function called getSpeciesByEnvironment() that creates a **New Promise**
    2) This function will use an axios.get call to firebase to pull down the data need.
    3a) Create a variable called ```const = demSpeciesByEnv;```
    3b) We will create a new empty array called ```const speciesByEnvironment = [ ];```
    4) Use object.keys to take ```demSpeciesByEnv``` and loop over the data and add a fbId.
                    ```Object.keys(demSpeciesByEnv).forEach(fbId) => {
        demSpeciesByEnv[fbId].id = fbId;
        speciesByEnvironment.push(demSpeciesByEnv[fbId]);```
    5) We will then ```resolve(speciesByEnvironment)```
    6) Follow up the resolve with a reject in case we encounter any errors.
             ```.catch((error) => reject(error));```
    7) Export the function.

**Comment by gregkorte** [comment]
In getEnvironmentWithSpecies:
 Are you getting just one environment or all environments? If just one, you'll want to pass the enviromentId in, otherwise you'll need a loop to iterate through each environment to get the species.
In getDestinationWithEnvAndSpecies:
 Same question. Are you getting just one or all?
