### ISSUE TITLE
Mock up

### ISSUE THREAD

**Issue by CharityBunyon** [nss-evening-cohort-10/nutshell-nautilus-explorer#9]
**Dashboard/Home**
![Dashboard_index](https://user-images.githubusercontent.com/26425684/68815592-6c6dd680-0641-11ea-9f9a-495fe943773f.jpg)

**Crew & Species Pages**
![crew_species](https://user-images.githubusercontent.com/26425684/68818232-f3bf4800-0649-11ea-8dcf-1590c92cec94.jpg)

**Destinations, Logs, & Environments**
![Logs_Destinations_Environments](https://user-images.githubusercontent.com/26425684/68818238-fb7eec80-0649-11ea-85b0-c6faf816d766.jpg)

**Comment by CharityBunyon** [comment]
![](https://files.slack.com/files-pri/T03F2SDTJ-FQ8855B1P/image_from_ios.jpg)

**Comment by CharityBunyon** [comment]
![Image from iOS](https://user-images.githubusercontent.com/52020883/68728019-bac09e00-058b-11ea-8e25-d6d596d8234f.jpg)

**Comment by evangdesigns** [comment]
**COLORS**
Bronze: `#cd7f32` (Navbar and card headers)
Crimson: `#c1272d` (Button Text, links, and sub-button background)

**FONT**
H tags: `font-family: 'Bebas Neue', cursive;`
p tags: `font-family: 'PT Sans', sans-serif;`

**Comment by evangdesigns** [comment]
**Nautilus Logo**
![nautilus_logo](https://user-images.githubusercontent.com/26425684/68817259-c624cf80-0646-11ea-90c4-1ac32d6e603b.png)

**Comment by CharityBunyon** [comment]
I found some cool images for the site.

https://unsplash.com/s/photos/nautical
